### PR TITLE
Prepare MicroPub Endpoint to insert photo into the checkin

### PR DESCRIPTION
**Pull request by danito**
Saves $_FILE['photo'] into file system and adds the proper html to the body.
Fix Array to string conversion when converting categories to hashtags and $content is_array.

### CODE REVIEW

**Comment by danito** [comment]
fixes #1251 
fixes #1257

**Comment by danito** [comment]
fixes #1257

**Comment by kylewm** [comment]
Can you reindent this section please? It looks to me like it adds an unmatched `{` but it's a little hard to tell.

**Comment by kylewm** [comment]
Thank you for re-indenting, I get it now and think the changes make sense :+1:

For future reference, it looks like your editor went one step too far and shifted *every* line four spaces to the left when it fixed up the indents...this [makes the diff](https://github.com/idno/Known/pull/1270/files) pretty hard to read (It thinks 195 lines changed, when really only a few of them actually changed)

**Comment by danito** [comment]
#blameNetbeans

**Comment by kylewm** [comment]
> #blameNetbeans

heh yeah, Emacs does the same thing.

**Comment by benwerd** [comment]
I think I introduced a breaking change by accepting another pull request. I apologize. Once 0.9.1 has been released, I'll do the work to merge this in.

**Comment by danito** [comment]
yes, I was just thinking about it, this log/debugging thing will break my PR. I'll pull and merge it, no big deal.

**Pull request closed without merging**
