### PR TITLE
Update jquery to v3.4.1, jquery-timeago to v1.6.7

### PR DESCRIPTION
**Pull request by lindner**
## Here's what I fixed or added:

- Switch to npm based distribution as the components one is poorly maintained.
- Changes appear non-impacting: https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/

## Here's why I did it:

- updating to more stable infra
- reducing entropy.

## Checklist:

- [ ] This pull request addresses a single issue
- [ ] If this code includes interface changes, I've included screenshots in this Pull Request thread
- [ ] I've adhered to [Known's style guide](http://docs.withknown.com/en/latest/developers/standards/) ([these codesniffer rules](http://docs.withknown.com/en/latest/developers/testing/#code-style-testing) might help!)
- [ ] My git branch is named in a descriptive way - i.e., yourname-summary-of-issue
- [ ] I've tested my code in-browser
- [ ] My code contains descriptive comments
- [ ] I've added tests where applicable, and...
- [ ] I can run the [unit tests](http://docs.withknown.com/en/latest/developers/testing/#unit-testing) successfully.

### CODE REVIEW

**Comment by mapkyca** [comment]
Although, it looks like the build is failing even on reload. Not sure if it's related...

**Comment by lindner** [comment]
Looks like this is the error:

```
PHP Fatal error:  Uncaught Error: Class
'Symfony\Component\ClassLoader\UniversalClassLoader' not found in
/home/travis/build/idno/known/Idno/start.php:110
```

**Comment by mapkyca** [comment]
Yeah, not sure whether that's related... can't see why a minor change in composer would affect that though....

**Comment by mapkyca** [comment]
Also, appears that composer isn't downloading the npm version of jquery... hmm

**Comment by mapkyca** [comment]
Maybe apropos, I'm thinking about moving to the composer class loader, but not sure when I'll have the time to get round to it

**Comment by mapkyca** [comment]
Try merging latest code and see if it passes build (updated symfony)

**Comment by lindner** [comment]
Yay - tests pass.

**Pull request merged**
