### PR TITLE
Remove documented support for Postgres

### LINKED ISSUE #3226: Postgres support status
## While trying to do this:
Trying Known out with Postgres
I created a config.ini with the following:
```
database = 'Postgres'
dbname = 'known_pg'
dbpass = '***'
dbuser = 'known'
dbhost = '127.0.0.1'
dbport = '5432'

filesystem = 'local'
uploadpath = '~/known/Uploads/'
```
## I encountered this error:
From my `error_log` file
> MySQL server has gone away

Connection tested and working via other means such as `pg_isready`

### PR DESCRIPTION
**Pull request by mediaformat**
## Here's what I fixed or added:
Remove documented support for Postgres 
- Fixes #3226 
- Modifies scope of #3216
## Here's why I did it:
Postgres support was removed in https://github.com/idno/known/commit/737502f98c51351562844df9203020b2e9300f29

## Checklist: 

- [x] This pull request addresses a single issue
- [x] My git branch is named in a descriptive way - i.e., yourname-summary-of-issue

### CODE REVIEW

**Comment by benwerd** [comment]
Aiieeeee.

I'm going to put this PR on hold for a second and try to bring back Postgres support this week. This was removed while I wasn't watching the project and I deeply regret it.

**Comment by mediaformat** [comment]
@benwerd If no one has been using Postgres with Known in the last 4 years, should we still support postgres migration in ActivityPub/Sprint 2? is this a blocker?

**Comment by benwerd** [comment]
@mediaformat Not a blocker for the ActivityPub project at all! I just want to bring it back online in the wider context. I guess we can remove it from the documentation for now and then I'll reinstate it when it's ready.

**Review by benwerd — APPROVED** [review]
I'm sad that this happened, but this PR brings the documentation into truthfulness. LG!

**Pull request merged**
