### PR TITLE
use Composer

### PR DESCRIPTION
**Pull request by kylewm**
Still very open to discussion of whether we really want to do this at all, but I'm sending the PR now in case it furthers that discussion.

And obviously this would be for *after* 0.9 ships.

Ref #1064

### CODE REVIEW

**Comment by benwerd** [comment]
Following subsequent comments from @kylewm, I'm closing this. Let me know if you think I should reopen.

**Comment by kylewm** [comment]
I think that's the right thing to do for now :cry:

**Comment by benwerd** [comment]
Boooooo. I'm sorry. :(

It sounds like the conflicts were mostly to do with plugins? I wonder if there's another way to manage that?

**Comment by kylewm** [comment]
> It sounds like the conflicts were mostly to do with plugins?

Yep

Ideally I guess I'd want a way of vendoring libraries so that they were namespaced specifically to that plugin. Then there is no way `IdnoPlugins\Reactions\Mf2\Parser` would conflict with `IdnoPlugins\IndieSyndicate\Mf2\Parser`. But that doesn't seem very realistic, since you'd have to edit your code and the code of the libraries that reference other libraries.

If we wanted to go all-in on Composer and use it to install the actual plugins themselves, then I guess it could resolve the conflicts. But that would mean nobody could install plugins without cli access and composer, and that's a non-starter.

**Pull request closed without merging**
