### PR TITLE
Adding Codesniffer to default distro

### PR DESCRIPTION
**Pull request by benwerd**
## Here's what I fixed or added:

Added PHP-Codesniffer library and config to default distribution.

## Here's why I did it:

It doesn't make much sense to have this sit in a separate repo, and the repo was referencing a version that was out of date.

## Checklist: (`[x]` to check/tick the boxes)

- [x] This pull request addresses a single issue
- [ ] If this code includes interface changes, I've included screenshots in this Pull Request thread
- [ ] I've adhered to [Known's style guide](http://docs.withknown.com/en/latest/developers/standards/) ([these codesniffer rules](http://docs.withknown.com/en/latest/developers/testing/#code-style-testing) might help!)
- [ ] My git branch is named in a descriptive way - i.e., yourname-summary-of-issue
- [ ] I've tested my code in-browser
- [ ] My code contains descriptive comments
- [ ] I've added tests where applicable, and...
- [ ] I can run the [unit tests](http://docs.withknown.com/en/latest/developers/testing/#unit-testing) successfully.

### CODE REVIEW

**Comment by mapkyca** [comment]
Why remove the Known PHP CS package (which also has a place for the Known config files)?

**Comment by benwerd** [comment]
A couple of reasons, but the main one is that the config file can then sit in the root, allowing us to leave it unspecified on the command line. The repo wasn't doing much, and it seems to me that something required to develop on the codebase should be referenced directly rather than through a wrapper.

**Comment by mapkyca** [comment]
Hmm.. fair enough but I was trying to remove the cruft that was building up in the root

**Comment by lindner** [comment]
I do think that having this in a separate repo is important for consistency across this repo and the plugins.  But there also needs to be a lot that needs to happen to get all the plugins updated to the latest.  ex:

- CI coverage
- rename master to main
- etc.

**Comment by benwerd** [comment]
I'm going to close this and take a different approach. The point about plugins is well-taken.

**Pull request closed without merging**
