### PR TITLE
Add comments to .htaccess about upload size workaround

### PR DESCRIPTION
**Pull request by lindner**
## Here's what I fixed or added:

I had mysterious problems with file uploads, figured it out and the default 8M php upload size limits was causing problems.

## Here's why I did it:

Decided to add a commented entry in the .htaccess file.  Should also probably add this to the diagnostics page?  Maybe add to FAQ as well?  At least this is a start....

## Checklist:

- [ ] This pull request addresses a single issue
- [ ] If this code includes interface changes, I've included screenshots in this Pull Request thread
- [ ] I've adhered to [Known's style guide](http://docs.withknown.com/en/latest/developers/standards/) ([these codesniffer rules](http://docs.withknown.com/en/latest/developers/testing/#code-style-testing) might help!)
- [ ] My git branch is named in a descriptive way - i.e., yourname-summary-of-issue
- [ ] I've tested my code in-browser
- [ ] My code contains descriptive comments
- [ ] I've added tests where applicable, and...
- [ ] I can run the [unit tests](http://docs.withknown.com/en/latest/developers/testing/#unit-testing) successfully.

### CODE REVIEW

**Comment by mapkyca** [comment]
TBH I'm tempted to remove everything except the rewrite stuff from the htaccess - my feeling is that this is more of a platform config thing rather than doing hacky things in htaccess.

**Comment by lindner** [comment]
Sure, but we should address the upload size issue somewhere,
especially because it's a php platform thing...

Maybe warn during install/warmup if phpinfo shows small values?

**Comment by benwerd** [comment]
There are unfortunately quite a few shared hosts who still _only_ allow you to change this in the htaccess, at least easily. I think the config stuff has to stay.

**Comment by mapkyca** [comment]
Hmmmm... maybe. My experience is that software with weird things in their .htaccess tends to fight with the server wide config which should be the canonical one. Generally people set stuff in the .htaccess and then the devs forget to update it, time moves on and you find that things don't work because the software's settings - generous at the time - are very conservative in $currentyear.

Wordpress for example only has rewrite rules in their distributed .htaccess, and I think this is the model we should follow.

But have it your way, this isn't the hill I want to die on.

**Pull request merged**
