### PR TITLE
Adjusting initial plugins

### PR DESCRIPTION
**Pull request by benwerd**
Removing Firefox and taking the style / footer JS plugins out of the default stack.

### CODE REVIEW

**Comment by mapkyca** [comment]
You also removed event, was this deliberate?

Also also, might be worth looking at #2209 - which looks like to be the case, but might be worth investigating why they're reporting it's not active by default.

**Comment by benwerd** [comment]
It was deliberate. Event is kind of shoddy. I'm inclined to pop it out into its own repo.

And yep. Weird that it wouldn't be on by default. Strongly suspect it's a difference between the public package and current master.

**Comment by mapkyca** [comment]
Rather see PRs than it getting bumped tbh, things that end in their own repos tend to end up falling off people's radar... certainly my own!

**Comment by benwerd** [comment]
For sure. I think I'm considering just wiping it; my take is, the fewer features to maintain, the better. Better to have a few core things that work really really well than a million that are kind of dubious.

**Comment by jgmac1106** [comment]
+1 to smaller core and allowing community plugins though I must say Known has gotten closest to a correct event better than any platform. Still an event indo plugin would be fine

**Comment by mapkyca** [comment]
Maybe put it up for adoption then. I don't like the idea of deleting code, and I know some people still use some of the functionality - e.g. rsvps

**Comment by mapkyca** [comment]
Also yeah, I think event isn't terrible. I've certainly done a fair amount of work re timezones. Probably just needs a bit of spit and polish

**Comment by jgmac1106** [comment]
In terms of being used yes most HWCs use somebody's Known site for events
and to accept RSVPs as Known is only event UI that works.

**Comment by mapkyca** [comment]
My vote would be to keep events in core, and instead knock off the rough edges. There are other plugins I'd get rid of or streamline first - e.g. comic. 

I'd also be tempted to spin off footerjs etc (which has the power to break the site), with a view to replacing this with something better, as well as build #1846

**Comment by jeremycherfas** [comment]
+1 for leaving Events in, even if it does have rough edges. It also works, which is good even if the code isn't super smooth.

**Pull request merged**
