### PR TITLE
Small hack to improve speed

### PR DESCRIPTION
**Pull request by physcocode**
This small hack reduced loading time of my test known site.

### CODE REVIEW

**Comment by physcocode** [comment]
will have a look again

**Comment by benwerd** [comment]
Hey @physcocode I hadn't had a chance to look at this yet - did you withdraw it because it wasn't working properly, or for some other reason?

**Comment by physcocode** [comment]
@benwerd  this was breaking something in the travis build so i thought of doing some more research before opening pulling request . (I was litrally caching on apache headers and had no ideas of consequences).

**Comment by physcocode** [comment]
I am reopening this cause it worked fine on all the machines i tested but i have no idea why it failed the travis build so miserably . (to be frank i don't have much idea about terminal tests like travis)

**Comment by kylewm** [comment]
Travis is flaky sometimes.

**Comment by kylewm** [comment]
@physocode I get an error running locally:

```
[Wed Feb 03 18:19:20.332741 2016] [core:alert] [pid 3855] [client 127.0.0.1:45530] /home/kmahan/projects/Known/.htaccess: Invalid command 'Header', perhaps misspelled or defined by a module not included in the server configuration
```

**Comment by kylewm** [comment]
`sudo a2enmod headers` to enable mod_headers got it working again.

**Comment by physcocode** [comment]
@kylewm thanks for the catch i thought most of apache install have mod_headers enabled by default (most of new setups do). I added `sudo a2enmod headers` into travis and also insured that people with mod_header disabled don't accidentally try to cache via headers.

**Pull request merged**
