### PR TITLE
Admin acl tests

### PR DESCRIPTION
**Pull request by mapkyca**
## Here's what I fixed or added:

Some tests for ACLs, some fixes for logged out users

## Here's why I did it:

ACLs weren't being tested, now they are.

Closes #1543

### CODE REVIEW

**Comment by mapkyca** [comment]
Hold off from merging just yet, I need to isolate some slug generation errors this is causing...

**Comment by benwerd** [comment]
@mapkyca Yep, way ahead of you :) Let's figure this out before it goes in. Thanks for writing tests though!

**Comment by mapkyca** [comment]
It is interesting... I think these issues aren't to do with the access tests per se, rather they've exposed a bug with object construction. Not sure what's going on, but it seems that getByID is returning an object with an incorrect UUID.

**Comment by mapkyca** [comment]
Ok, zeroing in... looks like there's a double save error going on, possibly with test, possibly with the generic data item.

An initial object is created in the database with a generic UUID, and _ID. Then a second object is saved with a corrected stub based UUID and a new _ID, with the correct UUID and the old _ID value present in the json blob.

This causes the value the constructed entities to look the same, but the getByID and getByUUID methods to return different values. This seems to be a new issue...

**Comment by mapkyca** [comment]
Further... this is damn weird. Save is only being called once, however it definitely seems to be inserting two records...

**Comment by mapkyca** [comment]
Ahh... it's a db state issue, combined with some other weirdness.

**Comment by mapkyca** [comment]
Also fixed a PHP 5.4 error for free.

**Pull request merged**
