### PR TITLE
Fork Awesome migration and enhancements

### LINKED ISSUE #2358: Consider a move from font-awesome to fork-awesome
**Is your feature request related to a problem? Please describe.**
Known pervasively makes use of font-awesome, which is a great project, but is now no longer a 100% free project. It has a commercial "pro" version.

**Describe the solution you'd like**
A new project called [fork-awesome](http://forkaweso.me/Fork-Awesome/) has been created that is 100% free and licensed appropriately for an open source project like Known. We should consider a switch to fork-awesome.

**Describe alternatives you've considered**
We could stay with font-awesome, we just won't have access to the "pro" level features/icons.

**Additional context**
I'm not certain that a switch is founded or worthwhile, but I thought I'd bring the existence of fork-awesome to the attention of the Known core team so that you could make an effective decision about how to proceed.

### PR DESCRIPTION
**Pull request by lindner**
## Here's what I fixed or added:

- Introduces version 1.1.7 of Fork Awesome
  - Update classes to fork-awesome canonical names
  - Use -o suffix instead of far- prefix for outline icons
  - Rename fas- to fa- for solid icons
  - Use fa-commenting-o instead of fa-comment-dots
  - Use fa-calendar-check-o instead of fa-calendar-alt for RSVP
  - Adds v5 compatibility shim for themes/plugins
  - Use fa-group for 'Members only' visibility
- Refactor Icon support for Profile links, adds support for many sites
  - Use new associative array to do mapping
- Add support for new protocol schemes
  - Secure Scuttlebutt (ssb)
  - Ethereum (ethereum)
  - XMPP (icon)
  - Spotify (icon)

Fixes #2358

## Here's why I did it:

Wanted better icons for my Profile and found this issue.

Fixes #2358

## Checklist:

- [x] This pull request addresses a single issue
- [ ] If this code includes interface changes, I've included screenshots in this Pull Request thread
- [ ] I've adhered to Known's style guide
- [ ] My git branch is named in a descriptive way - i.e., yourname-summary-of-issue
- [x] I've tested my code in-browser
- [x] My code contains descriptive comments
- [ ] I've added tests where applicable, and...
- [x] I can run the unit tests successfully.

### CODE REVIEW

**Comment by lindner** [comment]
Thoughts?

**Comment by mapkyca** [comment]
Hmm... I'm in two minds, now we've got the font awesome shim installed so it no longer breaks.

@benwerd , your thoughts?

**Comment by benwerd** [comment]
Sorry for my long delay here. I've been swamped with other stuff, but I need to spend more time on Known.

I'm heavily in favor of this. I don't know enough about forkawesome, but assuming the fork will be maintained, I think we should use it. I also think the associative mapping is great (but I also agree that it should really be stored - and ideally maintained - elsewhere). Thank you for all this work, @lindner!

**Comment by lindner** [comment]
I found one small bug in my prod testing on https://1500wordmtu.com/

https://github.com/lindner/known/commit/6f24ff27efd68596730358d275eeeb728ecf5a7c

will cherry pick in a moment.

**Pull request merged**
