### PR TITLE
Adding JSON+LD support

### PR DESCRIPTION
**Pull request by mapkyca**
## Here's what I fixed or added:

Adding JSON+LD support

Adds json+ld for site itself (including search function in google), user (including linking to social media posts), blog post, photos and media.

## Here's why I did it:

Structured data support is sort of the thing these days.

I'd love @edent 's input on this, as I understand this is right up your ally.

### CODE REVIEW

**Comment by edent** [comment]
Generally looks good. A couple of points.

` "@context" => "http://schema.org",` I think that should be https. Probably doesn't make a huge difference, but foot to be consistent.

Some of the data should include dates.

I'm a fan of microdata, but doesn't make too much difference. 

You can test using:
https://search.google.com/structured-data/testing-tool

**Comment by mapkyca** [comment]
Thanks for your help!

**Comment by mapkyca** [comment]
I've run it through the google tool, but yeah testing is good.

**Comment by mapkyca** [comment]
This might be helpful: https://www.npmjs.com/package/wct-structured-data-testing (grunt task, not phpunit tho)

**Pull request merged**
