### PR TITLE
Upgrade SCSS/CSS processing

### PR DESCRIPTION
**Pull request by lindner**
- Switch from csslint to stylelint
- Only check source scss files and apply standard fixes for whitespace etc.
- Combine duplicated properties
- Rerun build-css and make sure tests pass
- Use dart-sass module
- Remove most vendor prefixes
- Updated node packages
- Add docs

## Here's what I fixed or added:

See above

## Here's why I did it:

Keep Known using not dead projects like csslint.  Use idiomatic sass

## Checklist: (`[x]` to check/tick the boxes)

- [x] This pull request addresses a single issue
- [ ] If this code includes interface changes, I've included screenshots in this Pull Request thread
- [x] I've adhered to [Known's style guide](http://docs.withknown.com/en/latest/developers/standards/) ([these codesniffer rules](http://docs.withknown.com/en/latest/developers/testing/#code-style-testing) might help!)
- [x] My git branch is named in a descriptive way - i.e., yourname-summary-of-issue
- [x] I've tested my code in-browser
- [x] My code contains descriptive comments
- [x] I've added tests where applicable, and...
- [x] I can run the [unit tests](http://docs.withknown.com/en/latest/developers/testing/#unit-testing) successfully.

### CODE REVIEW

**Comment by lindner** [comment]
Checked in browsers. Everything looks good desktop/mobile

**Comment by lindner** [comment]
Anyone?

**Comment by benwerd** [comment]
Review coming tonight! Sorry for delay!

Ben Werdmuller
( http://goog_1933028737 )
werd.io ( http://werd.io ) | @benwerd ( https://twitter.com/benwerd )

(he/him)

**Review by benwerd — APPROVED** [review]
LGTM

**Pull request merged**
