### PR TITLE
Add optional field to posse links to store bare item ID

### PR DESCRIPTION
**Pull request by misuba**
This enhancement will open up the possibility of doing more in plugins with major social-network APIs.

### CODE REVIEW

**Comment by kylewm** [comment]
Just out of curiosity, what do you want to do with the bare ID that cannot be done with the syndication URL?

**Comment by misuba** [comment]
Make some other calls to the Twitter API from the Twitter plugin (or another plugin, I'm waffling on that). It would be nice not to have to fish IDs out of URLs, especially if the URL format ever changes.

**Comment by mapkyca** [comment]
There should be nothing preventing a plugin from listening events and adding this info of course.

**Comment by misuba** [comment]
...besides the total lack of documentation on events. :-)

I see the existing Twitter plugin calling the posse methods; that's all I'm going by.

**Comment by benwerd** [comment]
Agree on:

* documentation (we really need a concerted effort to improve this)
* using IDs over URIs

**Pull request merged**
