### PR TITLE
No forwarding

### PR DESCRIPTION
**Pull request by mapkyca**
Pages now return correct error code (as opposed to forwarding and losing the response code).

### CODE REVIEW

**Comment by benwerd** [comment]
Uh ... thinking about the user experience of this. Does this display the form on deniedContent when you're logged out? That would be neat.

**Comment by physcocode** [comment]
@benwerd i think this actually does show the login form on denied content

**Comment by mapkyca** [comment]
At the moment it doesn't.

I did originally include the login page on deniedContent, which worked, but 1) looked horrible ;) and 2) there's a case for having one page for login as a central point to override.

I was thinking about this on the way home from training, and I think maybe a good approach would be a "soft" redirect on deniedContent (window.location or meta refresh). That would preserve outward behaviour for users, but would mean you *would* get the correct HTTP error code back.

**Comment by benwerd** [comment]
That makes sense. User experience has to trump API considerations, always - but this would satisfy both.

**Pull request merged**
