### PR TITLE
Out of band headers are hard; use in-band data for api forwarding squish.

### PR DESCRIPTION
**Pull request by mapkyca**
Update:

* Avoids #1036 
* Closes #1038

### CODE REVIEW

**Comment by mapkyca** [comment]
Updated logic to avoid #1036

**Comment by mapkyca** [comment]
Bumping, as I'll be doing a bunch of api work soon

**Comment by mapkyca** [comment]
Resolved conflicts with latest code

**Comment by mapkyca** [comment]
Any comments? :)

**Comment by benwerd** [comment]
Uh oh. I may have introduced a conflict here by merging backwards?

**Comment by mapkyca** [comment]
Lemme check once I have coffee :)

**Comment by mapkyca** [comment]
Not sure why it was having a problem, but this should merge now.

I think I may have accidental conflated some patches somewhere along the line...

**Pull request merged**
