### PR TITLE
Adding web monetization

### PR DESCRIPTION
**Pull request by benwerd**
## Here's what I fixed or added:

Users can now add a web monetization pointer

## Here's why I did it:

We should be promoting distributed monetization.

## Checklist: (`[x]` to check/tick the boxes)

- [x] This pull request addresses a single issue
- [ ] If this code includes interface changes, I've included screenshots in this Pull Request thread
- [ ] I've adhered to [Known's style guide](http://docs.withknown.com/en/latest/developers/standards/) ([these codesniffer rules](http://docs.withknown.com/en/latest/developers/testing/#code-style-testing) might help!)
- [ ] My git branch is named in a descriptive way - i.e., yourname-summary-of-issue
- [ ] I've tested my code in-browser
- [ ] My code contains descriptive comments
- [ ] I've added tests where applicable, and...
- [ ] I can run the [unit tests](http://docs.withknown.com/en/latest/developers/testing/#unit-testing) successfully.

### CODE REVIEW

**Comment by lindner** [comment]
Does this always display on the home page or is it hidden?

**Comment by benwerd** [comment]
It's an option in the admin panel - there's no visible component.

**Comment by mapkyca** [comment]
Ahh... is Coil something new? (terrible name)

I wondered why my XRP position suddenly spiked.

**Comment by mapkyca** [comment]
Would be nice to accept BTC directly. IIRC some exchanges e.g blockchain have a payment API, or at least did way back when.

**Comment by benwerd** [comment]
It's not _very_ new, but it's gaining steam. See https://coil.com for more - and https://www.grantfortheweb.org/

**Comment by benwerd** [comment]
I wrote the Unlock plugin to allow Known site users to receive ETH directly - and obvs other coins are available. BTC isn't that suitable for site-to-site payments IMO because it's relatively slow and inflexible.

**Comment by mapkyca** [comment]
It's slower than a credit card, true, but so much faster than dealing with banks for overseas payments. These days half my clients pay me in crypto, especially in those places which have "issues" with money - i.e. China.

**Comment by mapkyca** [comment]
Different use cases obviously. Big into crypto these days :D

**Comment by benwerd** [comment]
Same - or rather, decentralization. But let's take the discussion off this PR and put it somewhere else ;)

**Comment by mapkyca** [comment]
Heh heh! You mean this isn't IRC?

**Comment by Cambridgeport90** [comment]
Good call... except it will be even cooler when more cryptocurrencies are supported. Hive is my favourite... because it was designed from the ground up to be for bloggers and creators.

**Pull request merged**
