### PR TITLE
Revert "Adding admin bypass to canRead"

### PR DESCRIPTION
**Pull request by erinjo**
Reverts idno/Known#1552

### CODE REVIEW

**Comment by physcocode** [comment]
@erinjo @mapkyca any particular reason for reverting ?

**Comment by erinjo** [comment]
@physcocode Hi Pranjal. Yes. We're working through some access permission updates. I reverted this because it allows site administrators to see other users' private posts.

**Comment by mapkyca** [comment]
So, the admin user as a special user is a pretty standard model for multiuser platforms (wordpress, elgg, etc), and is necessary for e.g. handling abusive posts, hellbanning, etc etc. 

It was also definitely how Known was _intended_ to work, see admin bypasses elsewhere in canEdit() etc, so a bypass on canRead() is definitely how it was _intended_ to work.

If by private posts you're really talking about drafts, and the issue where draft posts were appearing in a feed for admin users, then this will largely be resolved by #1559, meaning drafts can be hidden via a filter, and avoids using ACLs for this purpose.

**Comment by physcocode** [comment]
@mapkyca I was actually thinking same Admin needs to be "Admin" and canEdit goes hand to hand with canRead

**Comment by mapkyca** [comment]
Closing, no longer relevant.

**Pull request closed without merging**
