### PR TITLE
Upgrade to TinyMCE 5.0.4

### PR DESCRIPTION
**Pull request by lindner**
- See openUrl docs in https://github.com/tinymce/tinymce-docs/pull/1021/
- Switch to new postMessage based iframe communication channel.
- Remove custom theme, as the new default is minimal.
- Force usage of 'silver' theme on mobile due to [bug](https://github.com/tinymce/tinymce/issues/4818)
  with Boostrap and general poor UI of mobile theme. See [workaround](https://stackoverflow.com/questions/54579110/is-it-possible-to-disable-the-mobile-ui-features-in-tinymce-5)

## Here's what I fixed or added:

Upgraded to TinyMCE 5.0.4

## Here's why I did it:

Switch from the deprecated TinyMCE version to the one that's not quite ready yet (and VC funded, hmmm...)

Also see the [v5 announcement](https://go.tiny.cloud/blog/tinymce-5-power-meets-beauty/)

## Checklist:

- [ ] This pull request addresses a single issue
- [ ] If this code includes interface changes, I've included screenshots in this Pull Request thread
- [ ] I've adhered to Known's style guide
- [ ] My git branch is named in a descriptive way - i.e., yourname-summary-of-issue
- [ ] I've tested my code in-browser
- [ ] My code contains descriptive comments
- [ ] I've added tests where applicable, and...
- [ ] I can run the unit tests successfully.

### CODE REVIEW

**Comment by lindner** [comment]
Looks like there's also some more customization possible including drag-n-drop images and more.

Also might be interesting to make an IndieWeb plugin to automate some of the markup.  Could also add a people picker pretty easily using their new toolkit.

**Comment by mapkyca** [comment]
Thanks! I'm going to hold off on this for the moment, as when I tried using a more up to date tinymce it broke a lot of things (mobile, file uploads and some other things). Will try and kick the tires properly at the weekend, unless @benwerd gets there first.

**Comment by lindner** [comment]
Looks like there's also some more customization possible including drag-n-drop images and more.

Also might be interesting to make an IndieWeb plugin to automate some of the markup.  Could also add a people picker pretty easily using their new toolkit.

**Comment by lindner** [comment]
I directly addressed mobile and file uploads with this PR.  (there were definitely tricky parts with the updated APIs)

It might also be worthwhile to see if the 5.x line stabilizes a bit; but I do think it's worthwhile to move there and say goodbye to IE8 compatibility...

**Comment by mapkyca** [comment]
Yeah, I'm not against the move, and a while ago we also tried ditching Tinymce altogether in favour of Quill (which turned out to be... difficult). But in $CurrentYear, I'd actually throw my lot into maybe seeing if we could get Guttenberg working.

That's a little ways off though :)

**Comment by lindner** [comment]
Cool, maybe open an issue for upgraded editor experience for post v1?

**Comment by mapkyca** [comment]
Yep, that's definitely something to look at after 1.0. Tinymce has caused me many headaches over the year, and I still have an open bug to do with the new mobile skin...

**Comment by lindner** [comment]
Rebased

**Pull request merged**
