### PR TITLE
Allow stub console plugins

### PR DESCRIPTION
**Pull request by mapkyca**
## Here's what I fixed or added:

Allow php files in ConsolePlugins/ to be scanned for console plugins

## Here's why I did it:

It was time consuming to create full directory hierarchies when you just needed a quick console file.

### CODE REVIEW

**Comment by benwerd** [comment]
I wonder if this should be true for `IdnoPlugins` too?

**Comment by mapkyca** [comment]
Maybe, although "proper" plugins are always at least two files - the .php and the manifest, so we'd need to also provide a way of accounting for that.

**Comment by benwerd** [comment]
Oh, you're right. Never mind. I was thinking about consistency from a developer standpoint, but I don't think removing the manifests would be a great idea, fwiw.

**Comment by mapkyca** [comment]
Aye, and in any case I think we should "encourage" compartmentalisation in the main plugin hierarchy. It makes sense to allow stubs for console since they're almost always a single file, and I don't anticipate a massive ecosystem for console plugins..

**Comment by benwerd** [comment]
Yeah, I think most people don't know they exist, and might not be able to use them - which is fine.

**Pull request merged**
