### PR TITLE
Refs #831: Admins can't be admins when connecting via the API.

### PR DESCRIPTION
**Pull request by mapkyca**

### CODE REVIEW

**Comment by benwerd** [comment]
For now - but once it's a more OAuth-like API auth mechanism I want to bring it back.

**Comment by mapkyca** [comment]
Check my oauth plugin - perhaps some dusting off then bring into core?

**Comment by mapkyca** [comment]
Check my oauth plugin - perhaps some dusting off then bring into core?

**Comment by mapkyca** [comment]
Check my oauth plugin - perhaps some dusting off then bring into core?

**Pull request merged**
