### PR TITLE
Retroactive posse

### PR DESCRIPTION
**Pull request by matzoman**
#206 

Adding the possibility to POSSE an entry in edit mode. The syndication toggles are disabled when the entry was POSSE'd already. (Disabling only works when the twitter/fb/etc. plugin adds the `Entity::setPosseLinks` parameter 'account_id'.)

major changes:
- a new `Entity::publish()` function all plugins must use for the button "Publish".
- the function `Template::drawSyndication()` has a new parameter (the return value of `Entity::getPosseLinks()`)

I changed all plugins to use publish() and added the new parameter to all drawSyndication calls.

### CODE REVIEW

**Comment by physcocode** [comment]
wow this is blowing my  mind :+1:

**Comment by kylewm** [comment]
Insert that Tim and Eric mind blowing gif. Just checked this out on my install, and it works beautifully! Nicely done!

**Comment by benwerd** [comment]
I'm really looking forward to trying this out! Amazing work!

On Wednesday, February 3, 2016, Kyle Mahan <notifications@github.com> wrote:

> Insert that Tim and Eric mind blowing gif. Just checked this out on my
> install, and it works beautifully! Nicely done!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/pull/1190#issuecomment-179351288>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by benwerd** [comment]
Awesome!

**Comment by kylewm** [comment]
It's worth noting that now `Entity::saveDataFromInput` calls `Entity::publish` which calls `Entity::save`, which isn't super intuitive. Would it be worth renaming saveDataFromInput? `publishDataFromInput` doesn't make much sense; maybe `processFormInput` or something??

Granted renaming across plugins is a pain, but if we're going to do it might as well do it now.

**Comment by matzoman** [comment]
Thanks for all the kind words! It is a really engaging atmosphere in this project..

**Comment by danito** [comment]
:+1: 
Just my feature request: can we change the colour of an already syndicated service? When I hit edit now, I don't know if I already have pushed it to tw or FB (without checking first), is there an easy way to change the grey toggle to maybe black or orange where the posse link exists?

**Comment by srcr** [comment]
Awesome feature, thank @matzoman +1

**Pull request merged**
