### PR TITLE
Rebranding the legacy "audio" plugin as a "media" plugin. 

### PR DESCRIPTION
**Pull request by cleverdevil**
This effort was halfway done, and this change should bring it all the way there.

## Here's what I fixed or added:

Renamed "audio" in relevant places to "video" and picked a more appropriate icon.

## Here's why I did it:

Inconsistency makes me sad.

## Checklist:

- [x] This pull request addresses a single issue
- [ ] If this code includes interface changes, I've included screenshots in this Pull Request thread
- [x] I've adhered to Known's style guide
- [x] My git branch is named in a descriptive way - i.e., yourname-summary-of-issue
- [x] I've tested my code in-browser
- [x] My code contains descriptive comments
- [ ] I've added tests where applicable

### CODE REVIEW

**Comment by mapkyca** [comment]
Hmm... IIRC Audio used to be called Media, but it was changed since uploading video isn't reliable. Even to this day you still need to do a lot of transcoding to make something that's web compatible across browsers. 

I think the long term plan is to split this "media" plugin into audio and video, package audio and then keep video as an optional download for techy folk.

Right now, my vote would be to keep it as is, with video support as a hidden easter egg for people who are willing to take on the overhead of making sure their video is web ready, but I'll let @benwerd have the final say...

**Comment by cleverdevil** [comment]
I hear you, but right now it’s sort of in a halfway state, and is confusing if you upload a video, because it’s still listed under a category of “audio.” I’d rather just be up front that it supports both, but that the video bit has caveats or is in beta or testing or whatever. Also happy to help make it work better if we have specific cases where it’s broken or buggy.

**Comment by mapkyca** [comment]
Hmm... given a choice, I'd actually opt for removing references from video entirely. Like I said, having video work reliably isn't all that easy, so to keep things simple for non-technical users I'd prefer to move any video handling into it's own community supported plugin.

See discussion on #2141

**Comment by cleverdevil** [comment]
Good points @mapkyca and thanks for sharing the discussion. I'll await feedback from @benwerd, but would be happy to either work on getting this PR polished for merging into core, or to be given the directive that a community plugin would be a better path, and then to work with @mapkyca on creating a new plugin that is solely for video and includes his awesome transcoding features.

**Comment by mapkyca** [comment]
Bump at @benwerd

**Comment by mapkyca** [comment]
Closing for now

**Pull request closed without merging**
