### PR TITLE
add .m4a to supported Media types

### PR DESCRIPTION
**Pull request by physcocode**

### CODE REVIEW

**Comment by physcocode** [comment]
This added support for x-m4a and closes #731

**Comment by physcocode** [comment]
now its ok to merge (midnight code )

**Comment by kylewm** [comment]
Would you mind squashing these commits and giving them a descriptive comment (mention adding .m4a to media types)? Thanks!

**Comment by benwerd** [comment]
Backing up @kylewm - could you please make the commit messages a bit more descriptive? Thanks!

**Comment by benwerd** [comment]
This has now been added through another commit. Thanks for the pointer and code!

**Comment by physcocode** [comment]
@benwerd oops sorry i was busy in college studies and left both my pull request incomplete with no proper commit . Just saw request for proper commit . I would like to go full 'known' during my holidays :) with new PR's :)

**Pull request closed without merging**
